In [1]:
# imports

import pandas as pd
import numpy as np

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
# read dataset
df = pd.read_csv('melb_data.csv')
df.head()

Suburb           Address  Rooms Type      Price Method SellerG  \
0  Abbotsford      85 Turner St      2    h  1480000.0      S  Biggin   
1  Abbotsford   25 Bloomburg St      2    h  1035000.0      S  Biggin   
2  Abbotsford      5 Charles St      3    h  1465000.0     SP  Biggin   
3  Abbotsford  40 Federation La      3    h   850000.0     PI  Biggin   
4  Abbotsford       55a Park St      4    h  1600000.0     VB  Nelson   

        Date  Distance  Postcode  ...  Bathroom  Car  Landsize  BuildingArea  \
0  3/12/2016       2.5    3067.0  ...       1.0  1.0     202.0           NaN   
1  4/02/2016       2.5    3067.0  ...       1.0  0.0     156.0          79.0   
2  4/03/2017       2.5    3067.0  ...       2.0  0.0     134.0         150.0   
3  4/03/2017       2.5    3067.0  ...       2.0  1.0      94.0           NaN   
4  4/06/2016       2.5    3067.0  ...       1.0  2.0     120.0         142.0   

   YearBuilt  CouncilArea Lattitude  Longtitude             Regionname  \
0        NaN        Yarra  -37.7996    144.9984  Northern Metropolitan   
1     1900.0        Yarra  -37.8079    144.9934  Northern Metropolitan   
2     1900.0        Yarra  -37.8093    144.9944  Northern Metropolitan   
3        NaN        Yarra  -37.7969    144.9969  Northern Metropolitan   
4     2014.0        Yarra  -37.8072    144.9941  Northern Metropolitan   

  Propertycount  
0        4019.0  
1        4019.0  
2        4019.0  
3        4019.0  
4        4019.0  

[5 rows x 21 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Suburb         13580 non-null  object 
 1   Address        13580 non-null  object 
 2   Rooms          13580 non-null  int64  
 3   Type           13580 non-null  object 
 4   Price          13580 non-null  float64
 5   Method         13580 non-null  object 
 6   SellerG        13580 non-null  object 
 7   Date           13580 non-null  object 
 8   Distance       13580 non-null  float64
 9   Postcode       13580 non-null  float64
 10  Bedroom2       13580 non-null  float64
 11  Bathroom       13580 non-null  float64
 12  Car            13518 non-null  float64
 13  Landsize       13580 non-null  float64
 14  BuildingArea   7130 non-null   float64
 15  YearBuilt      8205 non-null   float64
 16  CouncilArea    12211 non-null  object 
 17  Lattitude      13580 non-null  float64
 18  Longti

In [5]:
df.nunique()

Suburb             314
Address          13378
Rooms                9
Type                 3
Price             2204
Method               5
SellerG            268
Date                58
Distance           202
Postcode           198
Bedroom2            12
Bathroom             9
Car                 11
Landsize          1448
BuildingArea       602
YearBuilt          144
CouncilArea         33
Lattitude         6503
Longtitude        7063
Regionname           8
Propertycount      311
dtype: int64

In [6]:
df.shape

(13580, 21)

In [7]:
col_to_use=['Suburb','Rooms','Type','Method','SellerG','Distance','Bedroom2','Bathroom','Car',
            'Landsize','BuildingArea','YearBuilt','CouncilArea','Regionname','Propertycount','Price']

data = df[col_to_use]
data.head()

Suburb  Rooms Type Method SellerG  Distance  Bedroom2  Bathroom  Car  \
0  Abbotsford      2    h      S  Biggin       2.5       2.0       1.0  1.0   
1  Abbotsford      2    h      S  Biggin       2.5       2.0       1.0  0.0   
2  Abbotsford      3    h     SP  Biggin       2.5       3.0       2.0  0.0   
3  Abbotsford      3    h     PI  Biggin       2.5       3.0       2.0  1.0   
4  Abbotsford      4    h     VB  Nelson       2.5       3.0       1.0  2.0   

   Landsize  BuildingArea  YearBuilt CouncilArea             Regionname  \
0     202.0           NaN        NaN       Yarra  Northern Metropolitan   
1     156.0          79.0     1900.0       Yarra  Northern Metropolitan   
2     134.0         150.0     1900.0       Yarra  Northern Metropolitan   
3      94.0           NaN        NaN       Yarra  Northern Metropolitan   
4     120.0         142.0     2014.0       Yarra  Northern Metropolitan   

   Propertycount      Price  
0         4019.0  1480000.0  
1         4019.0  1035000.0  
2         4019.0  1465000.0  
3         4019.0   850000.0  
4         4019.0  1600000.0

In [8]:
data.shape

(13580, 16)

In [9]:
# encoding

data = pd.get_dummies(data,drop_first = True)
data.head()

Rooms  Distance  Bedroom2  Bathroom  Car  Landsize  BuildingArea  \
0      2       2.5       2.0       1.0  1.0     202.0           NaN   
1      2       2.5       2.0       1.0  0.0     156.0          79.0   
2      3       2.5       3.0       2.0  0.0     134.0         150.0   
3      3       2.5       3.0       2.0  1.0      94.0           NaN   
4      4       2.5       3.0       1.0  2.0     120.0         142.0   

   YearBuilt  Propertycount      Price  ...  CouncilArea_Wyndham  \
0        NaN         4019.0  1480000.0  ...                False   
1     1900.0         4019.0  1035000.0  ...                False   
2     1900.0         4019.0  1465000.0  ...                False   
3        NaN         4019.0   850000.0  ...                False   
4     2014.0         4019.0  1600000.0  ...                False   

   CouncilArea_Yarra  CouncilArea_Yarra Ranges  Regionname_Eastern Victoria  \
0               True                     False                        False   
1               True                     False                        False   
2               True                     False                        False   
3               True                     False                        False   
4               True                     False                        False   

   Regionname_Northern Metropolitan  Regionname_Northern Victoria  \
0                              True                         False   
1                              True                         False   
2                              True                         False   
3                              True                         False   
4                              True                         False   

   Regionname_South-Eastern Metropolitan  Regionname_Southern Metropolitan  \
0                                  False                             False   
1                                  False                             False   
2                                  False                             False   
3                                  False                             False   
4                                  False                             False   

   Regionname_Western Metropolitan  Regionname_Western Victoria  
0                            False                        False  
1                            False                        False  
2                            False                        False  
3                            False                        False  
4                            False                        False  

[5 rows x 635 columns]

In [10]:
boo = data.isna().sum() > 0
nulls = data.isna().sum()
nulls[boo]

Car               62
BuildingArea    6450
YearBuilt       5375
dtype: int64

In [11]:
x = data.drop(columns = ['Price'])
y = data['Price']

In [12]:
from sklearn.model_selection import train_test_split


In [13]:
x_train , x_test , y_train , y_test = train_test_split(x,y , test_size= 0.3 )

In [14]:
nulls = x_train.isna().sum()
nulls[x_train.isna().sum() > 0]

Car               42
BuildingArea    4533
YearBuilt       3797
dtype: int64

In [15]:
# fill nulls

x_train['Car'] = x_train['Car'].fillna(0)

nulls = x_train.isna().sum()
nulls[x_train.isna().sum() > 0]

BuildingArea    4533
YearBuilt       3797
dtype: int64

In [16]:
nulls = x_test.isna().sum()
nulls[x_test.isna().sum() > 0]

Car               20
BuildingArea    1917
YearBuilt       1578
dtype: int64

In [17]:
x_test['Car'] = x_test['Car'].fillna(0)

nulls = x_test.isna().sum()
nulls[x_test.isna().sum() > 0]

BuildingArea    1917
YearBuilt       1578
dtype: int64

In [18]:
x_train['BuildingArea'] = x_train['BuildingArea'].fillna(x_train.BuildingArea.mean())
x_train['YearBuilt'] = x_train['YearBuilt'].fillna(x_train.YearBuilt.mean())
# x_train['CouncilArea'] = x_train['CouncilArea'].fillna(x_train.CouncilArea.mode()[0])

x_test['BuildingArea'] = x_test['BuildingArea'].fillna(x_test.BuildingArea.mean())
x_test['YearBuilt'] = x_test['YearBuilt'].fillna(x_test.YearBuilt.mean())
# x_test['CouncilArea'] = x_test['CouncilArea'].fillna(x_test.CouncilArea.mode()[0]) # return Series

# ----------------------------------- recap mode -------------------------------------------------

In [19]:
# mode
a = np.array([30,30,20,60,60,60,45,35])
a

array([30, 30, 20, 60, 60, 60, 45, 35])

In [20]:
from scipy import stats as st

In [21]:
st.mode(a)

ModeResult(mode=60, count=3)

In [22]:
# if multimode the result will be the smallest one
a = np.array([60,60,60,20,30,30,30,45,35])
a

array([60, 60, 60, 20, 30, 30, 30, 45, 35])

In [23]:
b = np.array([30,30,30,20,60,60,60,45,35])
b

array([30, 30, 30, 20, 60, 60, 60, 45, 35])

In [24]:
st.mode(a)

ModeResult(mode=30, count=3)

In [25]:
st.mode(b)

ModeResult(mode=30, count=3)

In [26]:
import statistics # if multimodal the result will be the first apperance one
statistics.mode(a)

60

In [27]:
statistics.mode(b)

30

In [28]:
# if no mode the result is the smallest num
f=np.array([30,50,20,4])
st.mode(f)

ModeResult(mode=4, count=1)

In [29]:
# if no mode the result is the first num
statistics.mode(f)

30

# ---------------------------------------------------------------------------------------------------

In [30]:
nulls = x_train.isna().sum()
nulls[x_train.isna().sum() > 0]

Series([], dtype: int64)

In [31]:
nulls = x_test.isna().sum()
nulls[x_test.isna().sum() > 0]

Series([], dtype: int64)

In [32]:
# data = data.drop(columns = ['CouncilArea'])
# data.isna().sum()

In [33]:
from sklearn.linear_model import LinearRegression

In [34]:
lin = LinearRegression()
lin.fit(x_train,y_train)

LinearRegression()

In [35]:
lin.score(x_test,y_test)

-270670607168.75888

In [36]:
lin.score(x_train,y_train)

0.7164696425560104

In [37]:
from sklearn.linear_model import Lasso
lasso_reg = Lasso(alpha=2)

lasso_reg.fit(x_train,y_train)

Lasso(alpha=2)

In [38]:
lasso_reg.score(x_test,y_test)

0.6697590603814729

In [39]:
lasso_reg.score(x_train,y_train)

0.7164456369194284

In [40]:
from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha=2)

ridge_reg.fit(x_train,y_train)

Ridge(alpha=2)

In [41]:
ridge_reg.score(x_test,y_test)

0.6788481145908796

In [42]:
ridge_reg.score(x_train,y_train)

0.7096120763433957